---
- hosts: localhost
  connection: local

  vars:
  - docker_repo: bestind/job-task

  tasks:
  - name: app deploy | Login Docker
    shell: cat ~/pwd.txt | docker login -u bestind --password-stdin

  - name: app deploy | Pull Docker
    shell: docker pull {{ docker_repo }}:{{ docker_tag }}

  - name: app deploy | Remove existing container
    shell: docker rm -f java_app
    ignore_errors: yes

  - name: app deploy | Start the new container
    shell: docker run -d
      -p 8081:8080
      --restart always
      --name java_app
      {{ docker_repo }}:{{ docker_tag }}
